import type { SystemUser, Plan, Student, Professional, Payment, Modality, ClassSchedule, WorkoutPlan } from "./types";

export const USERS: SystemUser[] = [
  { id: "u1", name: "Admin Master", email: "admin@titanhouse.com", password: "titan2024", role: "master", active: true },
  { id: "u2", name: "João Ferreira", email: "joao@titanhouse.com", password: "123456", role: "professor", active: true },
  { id: "u3", name: "Maria Santos", email: "maria@titanhouse.com", password: "123456", role: "atendente", active: true },
  { id: "u4", name: "Carlos Mendes", email: "carlos@titanhouse.com", password: "123456", role: "aluno", studentId: "s1", active: true },
  { id: "u5", name: "Fernanda Lima", email: "fernanda@titanhouse.com", password: "123456", role: "aluno", studentId: "s2", active: true },
  { id: "u6", name: "Rafael Costa", email: "rafa@titanhouse.com", password: "123456", role: "professor", active: true },
];

export const PLANS: Plan[] = [
  {
    id: "plan1",
    name: "Básico",
    price: 89.90,
    description: "Acesso completo à área de musculação com todos os equipamentos.",
    benefits: [
      "Acesso à sala de musculação",
      "Todos os equipamentos disponíveis",
      "Avaliação inicial gratuita",
      "Orientação básica de treino",
    ],
    startDate: "2024-01-01",
    endDate: "2026-12-31",
    color: "#428475",
  },
  {
    id: "plan2",
    name: "Intermediário",
    price: 129.90,
    description: "Tudo do Básico mais acesso às aulas coletivas de Zumba, Box e Bicicleta.",
    benefits: [
      "Todos os benefícios do Plano Básico",
      "Aulas de Zumba ilimitadas",
      "Aulas de Box ilimitadas",
      "Aulas de Bicicleta (Spinning) ilimitadas",
      "Acesso prioritário às aulas",
    ],
    startDate: "2024-01-01",
    endDate: "2026-12-31",
    color: "#89D7B7",
  },
  {
    id: "plan3",
    name: "Master",
    price: 189.90,
    description: "O plano completo com todos os benefícios, camisa oficial e avaliação física mensal.",
    benefits: [
      "Todos os benefícios do Plano Intermediário",
      "Camisa oficial TITAN HOUSE",
      "Avaliação física mensal",
      "Consultoria nutricional trimestral",
      "Acesso VIP às novas modalidades",
      "Desconto em suplementos parceiros",
    ],
    startDate: "2024-01-01",
    endDate: "2026-12-31",
    color: "#FFF4E1",
  },
];

export const PROFESSIONALS: Professional[] = [
  {
    id: "p1", name: "João Ferreira", age: 32, sex: "M", role: "Professor",
    phone: "(11) 99812-3456", workDays: ["Segunda", "Terça", "Quarta", "Quinta", "Sexta"],
    specialties: ["Musculação", "Hipertrofia", "Força"], active: true,
    photo: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=100&h=100&fit=crop",
  },
  {
    id: "p2", name: "Rafael Costa", age: 28, sex: "M", role: "Instrutor",
    phone: "(11) 98765-4321", workDays: ["Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado"],
    specialties: ["Box", "Funcional", "Condicionamento"], active: true,
    photo: "https://images.unsplash.com/photo-1534368786749-b63e05c90863?w=100&h=100&fit=crop",
  },
  {
    id: "p3", name: "Daniela Rocha", age: 26, sex: "F", role: "Atendente",
    phone: "(11) 97654-9876", workDays: ["Segunda", "Terça", "Quarta", "Quinta", "Sexta"],
    specialties: ["Recepção", "Cadastro", "Agendamento"], active: true,
    photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&h=100&fit=crop",
  },
  {
    id: "p4", name: "Priscila Nunes", age: 30, sex: "F", role: "Atendente",
    phone: "(11) 96543-2109", workDays: ["Terça", "Quarta", "Quinta", "Sexta", "Sábado"],
    specialties: ["Recepção", "Financeiro", "Zumba"], active: true,
    photo: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=100&h=100&fit=crop",
  },
  {
    id: "p5", name: "Luciana Matos", age: 34, sex: "F", role: "Instrutora" as any,
    phone: "(11) 95432-1098", workDays: ["Segunda", "Quarta", "Sexta", "Sábado"],
    specialties: ["Zumba", "Dança", "Bicicleta"], active: true,
    photo: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop",
  },
];

export const STUDENTS: Student[] = [
  {
    id: "s1", name: "Carlos Mendes", age: 28, cpf: "123.456.789-00",
    email: "carlos@email.com", phone: "(11) 98765-0001", sex: "M",
    planId: "plan3", planStartDate: "2025-01-10", planEndDate: "2026-01-10",
    paymentStatus: "pago", totalPaid: 2088.90, totalOwed: 0,
    advanceBalance: 189.90, nextPaymentDate: "2026-10-10", dueDate: "2026-10-10",
    trainerId: "p1", workoutPlanId: "wp1", active: true,
    photo: "https://images.unsplash.com/photo-1603415526960-f7e0328c63b1?w=100&h=100&fit=crop",
  },
  {
    id: "s2", name: "Fernanda Lima", age: 24, cpf: "234.567.890-11",
    email: "fernanda@email.com", phone: "(11) 98765-0002", sex: "F",
    planId: "plan2", planStartDate: "2025-03-15", planEndDate: "2026-03-15",
    paymentStatus: "adiantado", totalPaid: 909.30, totalOwed: 0,
    advanceBalance: 259.80, nextPaymentDate: "2026-11-15", dueDate: "2026-11-15",
    trainerId: "p1", workoutPlanId: "wp2", active: true,
    photo: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=100&h=100&fit=crop",
  },
  {
    id: "s3", name: "Bruno Alves", age: 35, cpf: "345.678.901-22",
    email: "bruno@email.com", phone: "(11) 98765-0003", sex: "M",
    planId: "plan1", planStartDate: "2025-02-01", planEndDate: "2026-02-01",
    paymentStatus: "atrasado", totalPaid: 449.50, totalOwed: 269.70,
    advanceBalance: 0, nextPaymentDate: "2026-07-01", dueDate: "2026-07-01",
    trainerId: "p2", workoutPlanId: "wp3", active: true,
    photo: "https://images.unsplash.com/photo-1567013127542-490d757e51fc?w=100&h=100&fit=crop",
  },
  {
    id: "s4", name: "Juliana Castro", age: 22, cpf: "456.789.012-33",
    email: "juliana@email.com", phone: "(11) 98765-0004", sex: "F",
    planId: "plan2", planStartDate: "2025-05-20", planEndDate: "2026-05-20",
    paymentStatus: "pendente", totalPaid: 519.60, totalOwed: 129.90,
    advanceBalance: 0, nextPaymentDate: "2026-09-20", dueDate: "2026-09-20",
    trainerId: "p1", workoutPlanId: "wp1", active: true,
    photo: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=100&h=100&fit=crop",
  },
  {
    id: "s5", name: "Ricardo Souza", age: 41, cpf: "567.890.123-44",
    email: "ricardo@email.com", phone: "(11) 98765-0005", sex: "M",
    planId: "plan3", planStartDate: "2024-11-05", planEndDate: "2025-11-05",
    paymentStatus: "atrasado", totalPaid: 1899.00, totalOwed: 379.80,
    advanceBalance: 0, nextPaymentDate: "2026-07-05", dueDate: "2026-07-05",
    trainerId: "p1", workoutPlanId: "wp2", active: true,
    photo: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=100&h=100&fit=crop",
  },
  {
    id: "s6", name: "Tatiana Ferreira", age: 29, cpf: "678.901.234-55",
    email: "tatiana@email.com", phone: "(11) 98765-0006", sex: "F",
    planId: "plan1", planStartDate: "2025-07-01", planEndDate: "2026-07-01",
    paymentStatus: "pago", totalPaid: 269.70, totalOwed: 0,
    advanceBalance: 0, nextPaymentDate: "2026-10-01", dueDate: "2026-10-01",
    trainerId: "p2", workoutPlanId: "wp3", active: true,
    photo: "https://images.unsplash.com/photo-1548142813-c348350df52b?w=100&h=100&fit=crop",
  },
  {
    id: "s7", name: "Gustavo Nery", age: 31, cpf: "789.012.345-66",
    email: "gustavo@email.com", phone: "(11) 98765-0007", sex: "M",
    planId: "plan2", planStartDate: "2025-04-10", planEndDate: "2026-04-10",
    paymentStatus: "pago", totalPaid: 649.50, totalOwed: 0,
    advanceBalance: 0, nextPaymentDate: "2026-10-10", dueDate: "2026-10-10",
    trainerId: "p2", workoutPlanId: "wp2", active: true,
    photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop",
  },
  {
    id: "s8", name: "Amanda Oliveira", age: 27, cpf: "890.123.456-77",
    email: "amanda@email.com", phone: "(11) 98765-0008", sex: "F",
    planId: "plan3", planStartDate: "2025-06-15", planEndDate: "2026-06-15",
    paymentStatus: "adiantado", totalPaid: 759.60, totalOwed: 0,
    advanceBalance: 189.90, nextPaymentDate: "2026-11-15", dueDate: "2026-11-15",
    trainerId: "p1", workoutPlanId: "wp1", active: true,
    photo: "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=100&h=100&fit=crop",
  },
];

export const PAYMENTS: Payment[] = [
  { id: "pay1", studentId: "s1", amount: 189.90, date: "2025-01-10", type: "payment", reference: "Jan/2025" },
  { id: "pay2", studentId: "s1", amount: 189.90, date: "2025-02-10", type: "payment", reference: "Fev/2025" },
  { id: "pay3", studentId: "s1", amount: 189.90, date: "2025-03-10", type: "payment", reference: "Mar/2025" },
  { id: "pay4", studentId: "s1", amount: 189.90, date: "2025-04-10", type: "payment", reference: "Abr/2025" },
  { id: "pay5", studentId: "s1", amount: 189.90, date: "2025-05-10", type: "payment", reference: "Mai/2025" },
  { id: "pay6", studentId: "s1", amount: 189.90, date: "2025-06-10", type: "payment", reference: "Jun/2025" },
  { id: "pay7", studentId: "s1", amount: 189.90, date: "2025-07-10", type: "payment", reference: "Jul/2025" },
  { id: "pay8", studentId: "s1", amount: 189.90, date: "2025-08-10", type: "payment", reference: "Ago/2025" },
  { id: "pay9", studentId: "s1", amount: 189.90, date: "2025-09-10", type: "payment", reference: "Set/2025" },
  { id: "pay10", studentId: "s1", amount: 189.90, date: "2025-10-10", type: "payment", reference: "Out/2025" },
  { id: "pay11", studentId: "s1", amount: 189.90, date: "2025-11-10", type: "payment", reference: "Nov/2025" },
  { id: "pay12", studentId: "s1", amount: 189.90, date: "2026-09-10", type: "advance", reference: "Out/2026 (Adiantado)" },
  { id: "pay13", studentId: "s2", amount: 129.90, date: "2025-03-15", type: "payment", reference: "Mar/2025" },
  { id: "pay14", studentId: "s2", amount: 129.90, date: "2025-04-15", type: "payment", reference: "Abr/2025" },
  { id: "pay15", studentId: "s2", amount: 129.90, date: "2025-05-15", type: "payment", reference: "Mai/2025" },
  { id: "pay16", studentId: "s2", amount: 129.90, date: "2025-06-15", type: "payment", reference: "Jun/2025" },
  { id: "pay17", studentId: "s2", amount: 129.90, date: "2025-07-15", type: "payment", reference: "Jul/2025" },
  { id: "pay18", studentId: "s2", amount: 129.90, date: "2025-08-15", type: "payment", reference: "Ago/2025" },
  { id: "pay19", studentId: "s2", amount: 129.90, date: "2025-09-15", type: "payment", reference: "Set/2025" },
  { id: "pay20", studentId: "s2", amount: 259.80, date: "2026-09-01", type: "advance", reference: "Out+Nov/2026 (Adiantado)" },
  { id: "pay21", studentId: "s3", amount: 89.90, date: "2025-02-01", type: "payment", reference: "Fev/2025" },
  { id: "pay22", studentId: "s3", amount: 89.90, date: "2025-03-01", type: "payment", reference: "Mar/2025" },
  { id: "pay23", studentId: "s3", amount: 89.90, date: "2025-04-01", type: "payment", reference: "Abr/2025" },
  { id: "pay24", studentId: "s3", amount: 89.90, date: "2025-05-01", type: "payment", reference: "Mai/2025" },
  { id: "pay25", studentId: "s3", amount: 89.90, date: "2025-06-01", type: "payment", reference: "Jun/2025" },
  { id: "pay26", studentId: "s4", amount: 129.90, date: "2025-05-20", type: "payment", reference: "Mai/2025" },
  { id: "pay27", studentId: "s4", amount: 129.90, date: "2025-06-20", type: "payment", reference: "Jun/2025" },
  { id: "pay28", studentId: "s4", amount: 129.90, date: "2025-07-20", type: "payment", reference: "Jul/2025" },
  { id: "pay29", studentId: "s4", amount: 129.90, date: "2025-08-20", type: "payment", reference: "Ago/2025" },
  { id: "pay30", studentId: "s5", amount: 189.90, date: "2024-11-05", type: "payment", reference: "Nov/2024" },
  { id: "pay31", studentId: "s5", amount: 189.90, date: "2024-12-05", type: "payment", reference: "Dez/2024" },
  { id: "pay32", studentId: "s5", amount: 189.90, date: "2025-01-05", type: "payment", reference: "Jan/2025" },
  { id: "pay33", studentId: "s5", amount: 189.90, date: "2025-02-05", type: "payment", reference: "Fev/2025" },
  { id: "pay34", studentId: "s5", amount: 189.90, date: "2025-03-05", type: "payment", reference: "Mar/2025" },
  { id: "pay35", studentId: "s5", amount: 189.90, date: "2025-04-05", type: "payment", reference: "Abr/2025" },
  { id: "pay36", studentId: "s5", amount: 189.90, date: "2025-05-05", type: "payment", reference: "Mai/2025" },
  { id: "pay37", studentId: "s5", amount: 189.90, date: "2025-06-05", type: "payment", reference: "Jun/2025" },
  { id: "pay38", studentId: "s5", amount: 189.90, date: "2025-07-05", type: "payment", reference: "Jul/2025" },
  { id: "pay39", studentId: "s5", amount: 189.90, date: "2025-08-05", type: "payment", reference: "Ago/2025" },
  { id: "pay40", studentId: "s6", amount: 89.90, date: "2025-07-01", type: "payment", reference: "Jul/2025" },
  { id: "pay41", studentId: "s6", amount: 89.90, date: "2025-08-01", type: "payment", reference: "Ago/2025" },
  { id: "pay42", studentId: "s6", amount: 89.90, date: "2025-09-01", type: "payment", reference: "Set/2025" },
  { id: "pay43", studentId: "s7", amount: 129.90, date: "2025-04-10", type: "payment", reference: "Abr/2025" },
  { id: "pay44", studentId: "s7", amount: 129.90, date: "2025-05-10", type: "payment", reference: "Mai/2025" },
  { id: "pay45", studentId: "s7", amount: 129.90, date: "2025-06-10", type: "payment", reference: "Jun/2025" },
  { id: "pay46", studentId: "s7", amount: 129.90, date: "2025-07-10", type: "payment", reference: "Jul/2025" },
  { id: "pay47", studentId: "s7", amount: 129.90, date: "2025-08-10", type: "payment", reference: "Ago/2025" },
  { id: "pay48", studentId: "s8", amount: 189.90, date: "2025-06-15", type: "payment", reference: "Jun/2025" },
  { id: "pay49", studentId: "s8", amount: 189.90, date: "2025-07-15", type: "payment", reference: "Jul/2025" },
  { id: "pay50", studentId: "s8", amount: 189.90, date: "2025-08-15", type: "payment", reference: "Ago/2025" },
  { id: "pay51", studentId: "s8", amount: 189.90, date: "2025-09-15", type: "payment", reference: "Set/2025" },
  { id: "pay52", studentId: "s8", amount: 189.90, date: "2026-09-10", type: "advance", reference: "Out/2026 (Adiantado)" },
];

export const MODALITIES: Modality[] = [
  { id: "mod1", name: "Musculação", description: "Sala completa com equipamentos de última geração para treino de força e hipertrofia.", icon: "🏋️", color: "#428475" },
  { id: "mod2", name: "Zumba", description: "Dança fitness de alto impacto que combina ritmos latinos com movimentos de dança.", icon: "💃", color: "#89D7B7" },
  { id: "mod3", name: "Box", description: "Treino de boxe funcional focado em condicionamento, agilidade e autodefesa.", icon: "🥊", color: "#FFF4E1" },
  { id: "mod4", name: "Bicicleta (Spinning)", description: "Aulas de ciclismo indoor com música animada e instrutor ao vivo.", icon: "🚴", color: "#428475" },
];

export const CLASSES: ClassSchedule[] = [
  { id: "c1", modalityId: "mod2", instructorId: "p5", dayOfWeek: "Segunda", time: "07:00", duration: 60, capacity: 20, enrolled: ["s2", "s4", "s8"], location: "Sala 2" },
  { id: "c2", modalityId: "mod2", instructorId: "p5", dayOfWeek: "Quarta", time: "07:00", duration: 60, capacity: 20, enrolled: ["s2", "s8"], location: "Sala 2" },
  { id: "c3", modalityId: "mod2", instructorId: "p5", dayOfWeek: "Sexta", time: "07:00", duration: 60, capacity: 20, enrolled: ["s2", "s4", "s8"], location: "Sala 2" },
  { id: "c4", modalityId: "mod3", instructorId: "p2", dayOfWeek: "Terça", time: "08:00", duration: 60, capacity: 15, enrolled: ["s5", "s7"], location: "Sala 3" },
  { id: "c5", modalityId: "mod3", instructorId: "p2", dayOfWeek: "Quinta", time: "08:00", duration: 60, capacity: 15, enrolled: ["s5", "s7"], location: "Sala 3" },
  { id: "c6", modalityId: "mod4", instructorId: "p5", dayOfWeek: "Segunda", time: "06:00", duration: 45, capacity: 25, enrolled: ["s1", "s2", "s3"], location: "Sala 4" },
  { id: "c7", modalityId: "mod4", instructorId: "p5", dayOfWeek: "Quarta", time: "06:00", duration: 45, capacity: 25, enrolled: ["s1", "s3"], location: "Sala 4" },
  { id: "c8", modalityId: "mod4", instructorId: "p5", dayOfWeek: "Sexta", time: "06:00", duration: 45, capacity: 25, enrolled: ["s1", "s2"], location: "Sala 4" },
  { id: "c9", modalityId: "mod2", instructorId: "p5", dayOfWeek: "Segunda", time: "18:00", duration: 60, capacity: 25, enrolled: ["s6"], location: "Sala 2" },
  { id: "c10", modalityId: "mod3", instructorId: "p2", dayOfWeek: "Terça", time: "19:00", duration: 60, capacity: 15, enrolled: ["s1", "s7", "s8"], location: "Sala 3" },
  { id: "c11", modalityId: "mod4", instructorId: "p5", dayOfWeek: "Quarta", time: "18:30", duration: 45, capacity: 25, enrolled: ["s4", "s6", "s8"], location: "Sala 4" },
  { id: "c12", modalityId: "mod2", instructorId: "p5", dayOfWeek: "Quinta", time: "09:00", duration: 60, capacity: 20, enrolled: [], location: "Sala 2" },
];

export const WORKOUT_PLANS: WorkoutPlan[] = [
  {
    id: "wp1",
    studentId: "s1",
    trainerId: "p1",
    modality: "Musculação",
    category: "Hipertrofia",
    schedule: [
      { day: "Segunda", workout: "A" },
      { day: "Terça", workout: "B" },
      { day: "Quarta", workout: "C" },
      { day: "Quinta", workout: "A" },
      { day: "Sexta", workout: "B" },
    ],
    days: [
      {
        letter: "A",
        label: "Treino A",
        focus: "Peito + Tríceps",
        exercises: [
          { id: "e1", name: "Supino Reto", machine: "Banco de Supino", location: "Sessão A-1", reps: 12, sets: 4, defaultWeight: 60, unit: "kg", tips: ["Mantenha os pés firmes no chão", "Desça a barra até o peito com controle", "Expire ao empurrar"], muscles: ["Peitoral maior", "Tríceps", "Deltóide anterior"] },
          { id: "e2", name: "Voador Peitoral", machine: "Máquina Peck Deck", location: "Sessão A-2", reps: 15, sets: 3, defaultWeight: 45, unit: "kg", tips: ["Mantenha os cotovelos levemente flexionados", "Abra os braços de forma controlada", "Sinta o alongamento no peitoral"], muscles: ["Peitoral maior", "Deltóide anterior"] },
          { id: "e3", name: "Tríceps Corda", machine: "Polia Alta + Corda", location: "Sessão A-3", reps: 12, sets: 4, defaultWeight: 25, unit: "kg", tips: ["Mantenha os cotovelos junto ao corpo", "Faça a extensão completa", "Abra a corda ao final do movimento"], muscles: ["Tríceps braquial"] },
          { id: "e4", name: "Supino Inclinado", machine: "Banco Inclinado", location: "Sessão A-4", reps: 10, sets: 3, defaultWeight: 50, unit: "kg", tips: ["Inclinação de 30-45 graus", "Foco na parte superior do peitoral", "Grip neutro para mais ativação"], muscles: ["Peitoral superior", "Deltóide anterior", "Tríceps"] },
          { id: "e5", name: "Mergulho entre Barras", machine: "Paralelas", location: "Sessão A-5", reps: 12, sets: 3, defaultWeight: 0, unit: "peso corporal", tips: ["Incline levemente para frente para ativar o peitoral", "Controle a descida", "Suba sem trancar os cotovelos"], muscles: ["Tríceps", "Peitoral inferior", "Deltóide"] },
        ],
      },
      {
        letter: "B",
        label: "Treino B",
        focus: "Costas + Bíceps",
        exercises: [
          { id: "e6", name: "Puxada Frontal", machine: "Máquina Puxada", location: "Sessão B-1", reps: 12, sets: 4, defaultWeight: 55, unit: "kg", tips: ["Puxe para o peito, não para o pescoço", "Abra bem o dorsal", "Controle a subida"], muscles: ["Latíssimo do dorso", "Bíceps", "Romboides"] },
          { id: "e7", name: "Remada Curvado", machine: "Barra Livre", location: "Sessão B-2", reps: 12, sets: 4, defaultWeight: 60, unit: "kg", tips: ["Mantenha a coluna neutra", "Puxe o cotovelo para trás", "Controle a descida"], muscles: ["Latíssimo do dorso", "Romboides", "Bíceps"] },
          { id: "e8", name: "Rosca Direta", machine: "Barra W", location: "Sessão B-3", reps: 12, sets: 3, defaultWeight: 20, unit: "kg", tips: ["Mantenha os cotovelos fixos", "Não balance o corpo", "Suba e desça com controle"], muscles: ["Bíceps braquial", "Braquiorradial"] },
          { id: "e9", name: "Rosca Scott", machine: "Banco Scott", location: "Sessão B-4", reps: 12, sets: 3, defaultWeight: 15, unit: "kg", tips: ["Apoie bem os braços no suporte", "Não estenda completamente ao descer", "Movimento isolado do bíceps"], muscles: ["Bíceps braquial"] },
          { id: "e10", name: "Puxada Fechada", machine: "Máquina Puxada", location: "Sessão B-5", reps: 10, sets: 3, defaultWeight: 50, unit: "kg", tips: ["Use a pegada supinada para mais ativação do bíceps", "Puxe até a clavícula", "Mantenha o peito para cima"], muscles: ["Latíssimo do dorso", "Bíceps"] },
        ],
      },
      {
        letter: "C",
        label: "Treino C",
        focus: "Pernas + Ombros",
        exercises: [
          { id: "e11", name: "Leg Press 45°", machine: "Máquina Leg Press", location: "Sessão C-1", reps: 12, sets: 4, defaultWeight: 120, unit: "kg", tips: ["Pés afastados na largura dos ombros", "Não trave os joelhos na extensão", "Desça até 90 graus"], muscles: ["Quadríceps", "Glúteos", "Isquiotibiais"] },
          { id: "e12", name: "Cadeira Extensora", machine: "Máquina Extensora", location: "Sessão C-2", reps: 15, sets: 3, defaultWeight: 60, unit: "kg", tips: ["Estenda completamente o joelho", "Controle a descida", "Não use impulso"], muscles: ["Quadríceps"] },
          { id: "e13", name: "Mesa Flexora", machine: "Máquina Flexora", location: "Sessão C-3", reps: 15, sets: 3, defaultWeight: 50, unit: "kg", tips: ["Flex complete dos joelhos", "Controle a descida", "Quadril fixo na mesa"], muscles: ["Isquiotibiais", "Glúteos"] },
          { id: "e14", name: "Desenvolvimento Máquina", machine: "Máquina Desenvolvimento", location: "Sessão C-4", reps: 12, sets: 4, defaultWeight: 35, unit: "kg", tips: ["Suba os braços até a extensão quase completa", "Não bata as mãos no topo", "Controle a descida"], muscles: ["Deltóide médio", "Deltóide anterior", "Tríceps"] },
          { id: "e15", name: "Elevação Lateral", machine: "Halteres", location: "Sessão C-5", reps: 15, sets: 3, defaultWeight: 8, unit: "kg", tips: ["Eleve até a altura dos ombros", "Mantenha leve flexão nos cotovelos", "Controle a descida"], muscles: ["Deltóide médio"] },
        ],
      },
    ],
    createdAt: "2025-01-15",
    updatedAt: "2026-08-10",
  },
  {
    id: "wp2",
    studentId: "s2",
    trainerId: "p1",
    modality: "Musculação",
    category: "Condicionamento",
    schedule: [
      { day: "Segunda", workout: "A" },
      { day: "Terça", workout: "B" },
      { day: "Quarta", workout: "C" },
      { day: "Quinta", workout: "A" },
      { day: "Sexta", workout: "B" },
    ],
    days: [
      {
        letter: "A",
        label: "Treino A",
        focus: "Peito + Ombros",
        exercises: [
          { id: "e16", name: "Supino Reto Halteres", machine: "Banco Reto + Halteres", location: "Sessão A-1", reps: 15, sets: 3, defaultWeight: 14, unit: "kg", tips: ["Use halteres para mais amplitude", "Pause no fundo do movimento", "Expire ao subir"], muscles: ["Peitoral", "Ombros", "Tríceps"] },
          { id: "e17", name: "Crucifixo Inclinado", machine: "Banco Inclinado + Halteres", location: "Sessão A-2", reps: 15, sets: 3, defaultWeight: 10, unit: "kg", tips: ["Foco no peitoral superior", "Controle o arco do movimento", "Não desça demais"], muscles: ["Peitoral superior", "Deltóide"] },
          { id: "e18", name: "Elevação Lateral", machine: "Halteres", location: "Sessão A-3", reps: 15, sets: 3, defaultWeight: 6, unit: "kg", tips: ["Cotovelos levemente flexionados", "Eleve até os ombros", "Não use impulso"], muscles: ["Deltóide médio"] },
          { id: "e19", name: "Desenvolvimento Dumbbell", machine: "Banco + Halteres", location: "Sessão A-4", reps: 12, sets: 3, defaultWeight: 12, unit: "kg", tips: ["Sente ereto no banco", "Alternar os braços para maior controle", "Expire ao subir"], muscles: ["Deltóide anterior", "Tríceps"] },
        ],
      },
      {
        letter: "B",
        label: "Treino B",
        focus: "Costas + Glúteos",
        exercises: [
          { id: "e20", name: "Puxada Frontal", machine: "Máquina Puxada", location: "Sessão B-1", reps: 12, sets: 3, defaultWeight: 40, unit: "kg", tips: ["Grip largo para mais ativação do dorsal", "Puxe o peito para a barra", "Controle a subida"], muscles: ["Latíssimo do dorso", "Bíceps"] },
          { id: "e21", name: "Remada Baixa", machine: "Polia Baixa", location: "Sessão B-2", reps: 12, sets: 3, defaultWeight: 40, unit: "kg", tips: ["Coluna reta", "Puxe para o umbigo", "Sem balanço do tronco"], muscles: ["Costas", "Bíceps"] },
          { id: "e22", name: "Cadeira Abdutora", machine: "Máquina Abdutora", location: "Sessão B-3", reps: 20, sets: 3, defaultWeight: 50, unit: "kg", tips: ["Abra bem as pernas", "Controle o retorno", "Sente ereta no banco"], muscles: ["Glúteo médio", "Piriforme"] },
          { id: "e23", name: "Extensão Lombar", machine: "Banco Lombar", location: "Sessão B-4", reps: 15, sets: 3, defaultWeight: 0, unit: "peso corporal", tips: ["Movimento controlado", "Não hiperextenda", "Contraia o glúteo no topo"], muscles: ["Eretores da coluna", "Glúteos"] },
        ],
      },
      {
        letter: "C",
        label: "Treino C",
        focus: "Pernas + Core",
        exercises: [
          { id: "e24", name: "Agachamento Livre", machine: "Rack de Agachamento", location: "Sessão C-1", reps: 15, sets: 3, defaultWeight: 30, unit: "kg", tips: ["Pés na largura do quadril", "Joelhos na direção dos pés", "Coluna neutra"], muscles: ["Quadríceps", "Glúteos", "Isquiotibiais"] },
          { id: "e25", name: "Leg Press 45°", machine: "Máquina Leg Press", location: "Sessão C-2", reps: 15, sets: 3, defaultWeight: 80, unit: "kg", tips: ["Pés altos para mais glúteo", "Não trave os joelhos", "Amplitude completa"], muscles: ["Quadríceps", "Glúteos"] },
          { id: "e26", name: "Cadeira Extensora", machine: "Máquina Extensora", location: "Sessão C-3", reps: 20, sets: 3, defaultWeight: 40, unit: "kg", tips: ["Estenda completamente", "Pausa no topo", "Controle a descida"], muscles: ["Quadríceps"] },
          { id: "e27", name: "Abdominal Crunch", machine: "Colchonete", location: "Sessão C-4", reps: 20, sets: 3, defaultWeight: 0, unit: "peso corporal", tips: ["Mãos atrás da cabeça, não puxe o pescoço", "Suba com o abdômen", "Controle a descida"], muscles: ["Reto abdominal", "Oblíquos"] },
        ],
      },
    ],
    createdAt: "2025-03-20",
    updatedAt: "2026-09-01",
  },
  {
    id: "wp3",
    studentId: "s3",
    trainerId: "p2",
    modality: "Musculação",
    category: "Força",
    schedule: [
      { day: "Segunda", workout: "A" },
      { day: "Terça", workout: "B" },
      { day: "Quarta", workout: "C" },
      { day: "Quinta", workout: "A" },
      { day: "Sexta", workout: "B" },
    ],
    days: [
      {
        letter: "A",
        label: "Treino A",
        focus: "Peito + Tríceps (Força)",
        exercises: [
          { id: "e28", name: "Supino Reto Barra", machine: "Banco de Supino + Barra", location: "Sessão A-1", reps: 5, sets: 5, defaultWeight: 100, unit: "kg", tips: ["Técnica antes de peso", "Arco natural no lombar", "Pés bem fixos"], muscles: ["Peitoral", "Tríceps", "Ombros"] },
          { id: "e29", name: "Supino Inclinado", machine: "Banco Inclinado + Barra", location: "Sessão A-2", reps: 6, sets: 4, defaultWeight: 80, unit: "kg", tips: ["Grip neutro para mais ativação", "Controled lowering", "Full range of motion"], muscles: ["Peitoral superior", "Deltóide"] },
          { id: "e30", name: "Tríceps Francês", machine: "Barra EZ + Banco", location: "Sessão A-3", reps: 8, sets: 4, defaultWeight: 30, unit: "kg", tips: ["Cotovelos apontados para cima", "Movimento somente no cotovelo", "Controle a descida"], muscles: ["Tríceps"] },
        ],
      },
      {
        letter: "B",
        label: "Treino B",
        focus: "Costas + Bíceps (Força)",
        exercises: [
          { id: "e31", name: "Barra Fixa", machine: "Barra Fixa", location: "Sessão B-1", reps: 6, sets: 4, defaultWeight: 0, unit: "peso corporal", tips: ["Ativação completa do dorsal", "Suba até o queixo", "Desça completamente"], muscles: ["Latíssimo do dorso", "Bíceps"] },
          { id: "e32", name: "Remada Curvado", machine: "Barra Olímpica", location: "Sessão B-2", reps: 5, sets: 5, defaultWeight: 80, unit: "kg", tips: ["Pegada pronada", "Puxe para o umbigo", "Mantenha a coluna neutra"], muscles: ["Costas", "Bíceps", "Trapézio"] },
          { id: "e33", name: "Rosca Direta Barra", machine: "Barra Reta", location: "Sessão B-3", reps: 8, sets: 4, defaultWeight: 30, unit: "kg", tips: ["Sem balanço do corpo", "Contração máxima no topo", "Controle a descida"], muscles: ["Bíceps"] },
        ],
      },
      {
        letter: "C",
        label: "Treino C",
        focus: "Pernas (Força)",
        exercises: [
          { id: "e34", name: "Agachamento Livre", machine: "Rack de Agachamento", location: "Sessão C-1", reps: 5, sets: 5, defaultWeight: 120, unit: "kg", tips: ["Posição baixa do bar", "Profundidade abaixo do paralelo", "Joelhos sobre os pés"], muscles: ["Quadríceps", "Glúteos", "Isquiotibiais"] },
          { id: "e35", name: "Terra (Deadlift)", machine: "Barra Olímpica + Anilhas", location: "Sessão C-2", reps: 5, sets: 4, defaultWeight: 120, unit: "kg", tips: ["Quadril mais alto que joelhos", "Costas neutras", "Barra próxima ao corpo"], muscles: ["Isquiotibiais", "Glúteos", "Lombar", "Trapézio"] },
          { id: "e36", name: "Leg Press 45°", machine: "Máquina Leg Press", location: "Sessão C-3", reps: 10, sets: 3, defaultWeight: 160, unit: "kg", tips: ["Amplitude completa", "Não trave os joelhos", "Respiração controlada"], muscles: ["Quadríceps", "Glúteos"] },
        ],
      },
    ],
    createdAt: "2025-02-05",
    updatedAt: "2026-06-15",
  },
];
